// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:adfbbeb8-eb10-4b80-a876-776f74e8cb51",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TETXl1XmH",
    "aws_user_pools_web_client_id": "5mcssci5en6u749g6tpccbi0ho",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rlbrwchr6basrdc3p6yr37ytpy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            },
            "speechGenerator": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Kendra",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
